version: '3'

services:
    web:
        build: .
        container_name: django_project
        command: gunicorn empproject.wsgi --bind 0.0.0.0:8000
        volumes:
            - .:/app 
        ports:
            - "8000:8000"
        depends_on:
            - mysqldb

    mysqldb:
        image: mysql:latest
        container_name: docker_mysqldb
        ports:
            - "3306:3306"
        volumes:
            - ./data/dbb:/var/lib/mysql 
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=jahurul25
            - MYSQL_PASSWORD=islam123
            - MYSQL_DATABASE=demodb
    
    nginx:
        image: nginx:latest
        container_name: nginx_docker
        ports:
            - 8080:80
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d 
        depends_on:
            - web
        restart: always