# Generated by Django 2.2.2 on 2022-02-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('mobile', models.CharField(max_length=20, unique=True, verbose_name='Mobile Number')),
                ('email', models.CharField(blank=True, max_length=20, null=True, verbose_name='Email Address')),
                ('designation', models.CharField(choices=[('1', 'CTO'), ('2', 'Senior Software Eng'), ('3', 'Software Eng')], max_length=1, verbose_name='Designation')),
                ('report_to', models.CharField(choices=[('1', 'CTO'), ('2', 'Senior Software Eng'), ('3', 'Software Eng')], max_length=1, verbose_name='Report To')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Employee Info',
                'db_table': 'employee_info',
                'managed': True,
            },
        ),
    ]
